[project]
name = "coinvision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.138.0",
    "joblib>=1.5.3",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "pydantic>=2.13.4",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.51",
    "torch>=2.12.1",
    "torchvision>=0.27.1",
]

[tool.uv]
dev-dependencies = []

[tool.fastapi]
entrypoint = "app.main:app"
